# Stage 1: Build React app
FROM node:18 AS build
WORKDIR /app
COPY . .
RUN yarn install && yarn build

# Stage 2: Serve with nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

# Overwrite nginx config to proxy API
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
