#***REMOVED***Stage***REMOVED***1:***REMOVED***Build***REMOVED***React***REMOVED***app
FROM***REMOVED***node:18***REMOVED***AS***REMOVED***build
WORKDIR***REMOVED***/app
COPY***REMOVED***.***REMOVED***.
RUN***REMOVED***yarn***REMOVED***install***REMOVED***&&***REMOVED***yarn***REMOVED***build

#***REMOVED***Stage***REMOVED***2:***REMOVED***Serve***REMOVED***with***REMOVED***nginx
FROM***REMOVED***nginx:alpine
COPY***REMOVED***--from=build***REMOVED***/app/build***REMOVED***/usr/share/nginx/html

#***REMOVED***Overwrite***REMOVED***nginx***REMOVED***config***REMOVED***to***REMOVED***proxy***REMOVED***API
RUN***REMOVED***rm***REMOVED***/etc/nginx/conf.d/default.conf
COPY***REMOVED***nginx.conf***REMOVED***/etc/nginx/conf.d/

EXPOSE***REMOVED***80
CMD***REMOVED***["nginx",***REMOVED***"-g",***REMOVED***"daemon***REMOVED***off;"]
