import***REMOVED***{***REMOVED***Routes,***REMOVED***Route***REMOVED***}***REMOVED***from***REMOVED***"react-router-dom";
import***REMOVED***Register***REMOVED***from***REMOVED***"../views/Auth/pages/Register";
import***REMOVED***Login***REMOVED***from***REMOVED***"../views/Auth/pages/Login";
import***REMOVED***HomePage***REMOVED***from***REMOVED***"src/views/Store/Home";
import***REMOVED***Dashboard***REMOVED***from***REMOVED***"src/views/Admin/Dashboard";
import***REMOVED***AdminDashboard***REMOVED***from***REMOVED***"src/layouts/DashboardLayout";
import***REMOVED***Category***REMOVED***from***REMOVED***"src/views/Admin/Category";
import***REMOVED***Attribute***REMOVED***from***REMOVED***"src/views/Admin/Attribute";
import***REMOVED***StoreLayout***REMOVED***from***REMOVED***"src/layouts/StoreLayout";
import***REMOVED***Product***REMOVED***from***REMOVED***"src/views/Admin/Product";
const***REMOVED***AppRoutes***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Routes>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Route***REMOVED***element={<StoreLayout***REMOVED***/>}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Route***REMOVED***path="/"***REMOVED***element={<HomePage***REMOVED***/>}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Route>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Route***REMOVED***path="/admin"***REMOVED***element={<AdminDashboard***REMOVED***/>}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Route***REMOVED***path="dashboard"***REMOVED***element={<Dashboard***REMOVED***/>}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Route***REMOVED***path="product"***REMOVED***element={<Product***REMOVED***/>}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Route***REMOVED***path="category"***REMOVED***element={<Category***REMOVED***/>}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Route***REMOVED***path="attribute"***REMOVED***element={<Attribute***REMOVED***/>}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Route***REMOVED***path="category/*"***REMOVED***element={<Category***REMOVED***/>}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Route>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Route***REMOVED***path="/register"***REMOVED***element={<Register***REMOVED***/>}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Route***REMOVED***path="/login"***REMOVED***element={<Login***REMOVED***/>}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED***</Routes>
***REMOVED******REMOVED***);
};

export***REMOVED***default***REMOVED***AppRoutes;
