export***REMOVED***const***REMOVED***BASE_URL***REMOVED***=***REMOVED***"https://localhost:7021/api"


export***REMOVED***const***REMOVED***AUTHENTICATION***REMOVED***=***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***ACTION_TYPES:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***LOGIN:***REMOVED***'AUTHENTICATION/LOGIN',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***REGISTER:***REMOVED***'AUTHENTICATION/REGISTER',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***VERIFY_OTP:***REMOVED***'AUTHENTICATION/VERIFY_OTP',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***RESEND_OTP:***REMOVED***'AUTHENTICATION/RESEND_OTP',
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***URL_API:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***LOGIN_API:***REMOVED******REMOVED***`${BASE_URL}/auth/login`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***REGISTER_API:***REMOVED******REMOVED***`${BASE_URL}/auth/register`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***VERIFY_OTP:***REMOVED******REMOVED***`${BASE_URL}/auth/verify-otp`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***RESEND_OTP:***REMOVED******REMOVED***`${BASE_URL}/auth/resend-otp`,
***REMOVED******REMOVED******REMOVED******REMOVED***}
}