export***REMOVED***const***REMOVED***BASE_URL***REMOVED***=***REMOVED***"https://localhost:7021/api"


export***REMOVED***const***REMOVED***AUTHENTICATION***REMOVED***=***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***ACTION_TYPES:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***LOGIN:***REMOVED***'AUTHENTICATION/LOGIN',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***REGISTER:***REMOVED***'AUTHENTICATION/REGISTER',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***VERIFY_OTP:***REMOVED***'AUTHENTICATION/VERIFY_OTP',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***RESEND_OTP:***REMOVED***'AUTHENTICATION/RESEND_OTP',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***REFRESH_TOKEN:***REMOVED***'AUTHENTICATION/REFRESH_TOKEN',
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***URL_API:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***LOGIN_API:***REMOVED******REMOVED***`${BASE_URL}/auth/login`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***REGISTER_API:***REMOVED******REMOVED***`${BASE_URL}/auth/register`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***VERIFY_OTP:***REMOVED******REMOVED***`${BASE_URL}/auth/verify-otp`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***RESEND_OTP:***REMOVED******REMOVED***`${BASE_URL}/auth/resend-otp`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***REFRESH_TOKEN_API:***REMOVED******REMOVED***`${BASE_URL}/auth/refresh-token`,
***REMOVED******REMOVED******REMOVED******REMOVED***}
}

export***REMOVED***const***REMOVED***CATEGORY***REMOVED***=***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***ACTION_TYPES:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***GET_ALL:***REMOVED***'CATEGORY/GET_ALL',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***CREATE:***REMOVED***'CATEGORY/CREATE',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***UPDATE:***REMOVED***'CATEGORY/UPDATE',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***DELETE:***REMOVED***'CATEGORY/DELETE',
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***URL_API:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***GET_ALL_API:***REMOVED******REMOVED***`${BASE_URL}/category/get-paging-category`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***CREATE_API:***REMOVED******REMOVED***`${BASE_URL}/category`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***UPDATE_API:***REMOVED******REMOVED***`${BASE_URL}/category`,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***DELETE_API:***REMOVED******REMOVED***`${BASE_URL}/category`,
***REMOVED******REMOVED******REMOVED******REMOVED***}
}