import***REMOVED***React***REMOVED***from***REMOVED***"react";
import***REMOVED***{***REMOVED***useQuery***REMOVED***}***REMOVED***from***REMOVED***"@tanstack/react-query";
import***REMOVED***categoryApi***REMOVED***from***REMOVED***"src/services/api/Category";
import***REMOVED***{***REMOVED***ICategory***REMOVED***}***REMOVED***from***REMOVED***"src/Interfaces/ICategory";
import***REMOVED***formatVietnamTime***REMOVED***from***REMOVED***"src/utils/formatVietnamTime";
import***REMOVED***{***REMOVED***CSSProperties***REMOVED***}***REMOVED***from***REMOVED***"react";

const***REMOVED***CategoryTable***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***data:***REMOVED***categories,***REMOVED***isLoading,***REMOVED***error***REMOVED***}***REMOVED***=***REMOVED***useQuery({
***REMOVED******REMOVED******REMOVED******REMOVED***queryKey:***REMOVED***["categories"],
***REMOVED******REMOVED******REMOVED******REMOVED***queryFn:***REMOVED***async***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***response***REMOVED***=***REMOVED***await***REMOVED***categoryApi.getPagingApi({***REMOVED***pageNumber:***REMOVED***1,***REMOVED***pageSize:***REMOVED***10***REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***response.data.data.$values;
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED***});

***REMOVED******REMOVED***if***REMOVED***(isLoading)***REMOVED***return***REMOVED***<p***REMOVED***style={{***REMOVED***textAlign:***REMOVED***"center",***REMOVED***fontWeight:***REMOVED***"bold"***REMOVED***}}>Đang***REMOVED***tải...</p>;
***REMOVED******REMOVED***if***REMOVED***(error)***REMOVED***return***REMOVED***<p***REMOVED***style={{***REMOVED***color:***REMOVED***"red",***REMOVED***textAlign:***REMOVED***"center"***REMOVED***}}>Lỗi:***REMOVED***{error.message}</p>;

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***style={styles.tableContainer}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<table***REMOVED***style={styles.table}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<thead>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<tr>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<th***REMOVED***style={styles.header}>STT</th>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<th***REMOVED***style={styles.header}>Mã***REMOVED***danh***REMOVED***mục</th>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<th***REMOVED***style={styles.header}>Tên***REMOVED***Danh***REMOVED***Mục</th>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<th***REMOVED***style={styles.header}>Người***REMOVED***tạo</th>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<th***REMOVED***style={styles.header}>Cập***REMOVED***nhật</th>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</tr>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</thead>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<tbody>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{categories?.map((category:***REMOVED***ICategory,***REMOVED***index:***REMOVED***number)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<tr***REMOVED***key={category.categoryId}***REMOVED***style={styles.row}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<td***REMOVED***style={styles.centerText}>{index***REMOVED***+***REMOVED***1}</td>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<td***REMOVED***style={styles.centerText}>{category.categoryId}</td>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<td***REMOVED***style={styles.cell}>{category.categoryName}</td>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<td***REMOVED***style={styles.cell}>{category?.creator?.fullName***REMOVED***||***REMOVED***"Không***REMOVED***có***REMOVED***dữ***REMOVED***liệu"}</td>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<td***REMOVED***style={styles.cell}>{formatVietnamTime(category.updatedAt)}</td>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</tr>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</tbody>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</table>
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED***);
};

//***REMOVED***✅***REMOVED***Định***REMOVED***nghĩa***REMOVED***CSS***REMOVED***chuẩn***REMOVED***với***REMOVED***viền***REMOVED***giữa***REMOVED***các***REMOVED***cột
const***REMOVED***styles:***REMOVED***Record<string,***REMOVED***CSSProperties>***REMOVED***=***REMOVED***{
***REMOVED******REMOVED***tableContainer:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***width:***REMOVED***"100%",
***REMOVED******REMOVED******REMOVED******REMOVED***overflowX:***REMOVED***"auto"***REMOVED***as***REMOVED***"auto",
***REMOVED******REMOVED******REMOVED******REMOVED***padding:***REMOVED***"10px",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***table:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***width:***REMOVED***"100%",
***REMOVED******REMOVED******REMOVED******REMOVED***borderCollapse:***REMOVED***"collapse",
***REMOVED******REMOVED******REMOVED******REMOVED***backgroundColor:***REMOVED***"white",
***REMOVED******REMOVED******REMOVED******REMOVED***borderRadius:***REMOVED***"8px",
***REMOVED******REMOVED******REMOVED******REMOVED***boxShadow:***REMOVED***"0px***REMOVED***2px***REMOVED***5px***REMOVED***rgba(0,***REMOVED***0,***REMOVED***0,***REMOVED***0.1)",
***REMOVED******REMOVED******REMOVED******REMOVED***overflow:***REMOVED***"hidden",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***header:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***backgroundColor:***REMOVED***"#007bff",
***REMOVED******REMOVED******REMOVED******REMOVED***color:***REMOVED***"white",
***REMOVED******REMOVED******REMOVED******REMOVED***fontWeight:***REMOVED***"bold",
***REMOVED******REMOVED******REMOVED******REMOVED***padding:***REMOVED***"10px",
***REMOVED******REMOVED******REMOVED******REMOVED***textAlign:***REMOVED***"left",
***REMOVED******REMOVED******REMOVED******REMOVED***borderBottom:***REMOVED***"2px***REMOVED***solid***REMOVED***#ddd",
***REMOVED******REMOVED******REMOVED******REMOVED***borderRight:***REMOVED***"1px***REMOVED***solid***REMOVED***#ddd",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***row:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***borderBottom:***REMOVED***"1px***REMOVED***solid***REMOVED***#ddd",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***centerText:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***textAlign:***REMOVED***"start",
***REMOVED******REMOVED******REMOVED******REMOVED***fontWeight:***REMOVED***"bold",
***REMOVED******REMOVED******REMOVED******REMOVED***padding:***REMOVED***"10px",
***REMOVED******REMOVED******REMOVED******REMOVED***borderRight:***REMOVED***"1px***REMOVED***solid***REMOVED***#ddd",
***REMOVED******REMOVED***},
***REMOVED******REMOVED***cell:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***padding:***REMOVED***"10px",
***REMOVED******REMOVED******REMOVED******REMOVED***borderRight:***REMOVED***"1px***REMOVED***solid***REMOVED***#ddd",
***REMOVED******REMOVED***},
};

export***REMOVED***default***REMOVED***CategoryTable;
