import***REMOVED***React***REMOVED***from***REMOVED***"react";
import***REMOVED***{
***REMOVED******REMOVED***Breadcrumbs,
***REMOVED******REMOVED***Typography,
***REMOVED******REMOVED***Link***REMOVED***as***REMOVED***MuiLink,
}***REMOVED***from***REMOVED***"@mui/material";
import***REMOVED***ChevronRightIcon***REMOVED***from***REMOVED***"@mui/icons-material/ChevronRight";
import***REMOVED***HomeIcon***REMOVED***from***REMOVED***"@mui/icons-material/Home";
import***REMOVED***{***REMOVED***Link***REMOVED***as***REMOVED***RouterLink***REMOVED***}***REMOVED***from***REMOVED***"react-router-dom";

export***REMOVED***interface***REMOVED***BreadcrumbItem***REMOVED***{
***REMOVED******REMOVED***categoryId?:***REMOVED***number;
***REMOVED******REMOVED***categoryName?:***REMOVED***string;
}

interface***REMOVED***BreadcrumbNavigationProps***REMOVED***{
***REMOVED******REMOVED***items?:***REMOVED***BreadcrumbItem[];
***REMOVED******REMOVED***pageTitle:***REMOVED***string;***REMOVED***//***REMOVED***Tên***REMOVED***trang***REMOVED***hiện***REMOVED***tại***REMOVED***(Trang***REMOVED***chủ***REMOVED***>***REMOVED***Tên***REMOVED***trang)
***REMOVED******REMOVED***pageUrl:***REMOVED***string;***REMOVED***//***REMOVED***URL***REMOVED***của***REMOVED***trang***REMOVED***hiện***REMOVED***tại***REMOVED***để***REMOVED***dẫn***REMOVED***đến***REMOVED***khi***REMOVED***click
}

const***REMOVED***BreadcrumbNavigation:***REMOVED***React.FC<BreadcrumbNavigationProps>***REMOVED***=***REMOVED***({
***REMOVED******REMOVED***items***REMOVED***=***REMOVED***[],
***REMOVED******REMOVED***pageTitle,
***REMOVED******REMOVED***pageUrl,
})***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***validCrumbs***REMOVED***=***REMOVED***items.filter((b)***REMOVED***=>***REMOVED***b.categoryId***REMOVED***!==***REMOVED***-1);

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Breadcrumbs
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***aria-label="breadcrumb"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***separator={<ChevronRightIcon***REMOVED***fontSize="small"***REMOVED***sx={{***REMOVED***mx:***REMOVED***-1***REMOVED***}}***REMOVED***/>}
***REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Trang***REMOVED***chủ***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<MuiLink
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***component={RouterLink}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***to="/admin/dashboard"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***color="inherit"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***underline="hover"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sx={{***REMOVED***display:***REMOVED***"flex",***REMOVED***alignItems:***REMOVED***"center",***REMOVED***gap:***REMOVED***0.5***REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<HomeIcon***REMOVED***fontSize="small"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Trang***REMOVED***chủ
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</MuiLink>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Tên***REMOVED***trang***REMOVED***hiện***REMOVED***tại***REMOVED***và***REMOVED***clickable***REMOVED***nếu***REMOVED***có***REMOVED***breadcrumbs***REMOVED***con***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{validCrumbs.length***REMOVED***>***REMOVED***0***REMOVED***?***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<MuiLink
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***component={RouterLink}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***to={pageUrl}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***color="inherit"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***underline="hover"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{pageTitle}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</MuiLink>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)***REMOVED***:***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Typography***REMOVED***color="text.primary">{pageTitle}</Typography>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Breadcrumb***REMOVED***động:***REMOVED***Danh***REMOVED***mục***REMOVED***con***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{validCrumbs.length***REMOVED***>***REMOVED***0***REMOVED***&&
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***validCrumbs.map((item,***REMOVED***index)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***isLast***REMOVED***=***REMOVED***index***REMOVED***===***REMOVED***validCrumbs.length***REMOVED***-***REMOVED***1;
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***path***REMOVED***=
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"/admin/category/"***REMOVED***+
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***validCrumbs
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***.slice(0,***REMOVED***index***REMOVED***+***REMOVED***1)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***.map((i)***REMOVED***=>***REMOVED***i.categoryId)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***.join("/");

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***isLast***REMOVED***?***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Typography***REMOVED***key={item.categoryId}***REMOVED***color="text.primary">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{item.categoryName}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Typography>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)***REMOVED***:***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<MuiLink
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***key={item.categoryId}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***component={RouterLink}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***to={path}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***underline="hover"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***color="inherit"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{item.categoryName}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</MuiLink>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***})}
***REMOVED******REMOVED******REMOVED******REMOVED***</Breadcrumbs>
***REMOVED******REMOVED***);
};

export***REMOVED***default***REMOVED***BreadcrumbNavigation;
