import***REMOVED***React***REMOVED***from***REMOVED***"react";
import***REMOVED***{***REMOVED***Menu,***REMOVED***MenuItem,***REMOVED***ListItemIcon,***REMOVED***ListItemText***REMOVED***}***REMOVED***from***REMOVED***"@mui/material";
import***REMOVED***{***REMOVED***IContextMenu***REMOVED***}***REMOVED***from***REMOVED***"src/Interfaces/IContextMenu";

interface***REMOVED***Props<T***REMOVED***=***REMOVED***any>***REMOVED***{
***REMOVED******REMOVED***items:***REMOVED***IContextMenu<T>[];
***REMOVED******REMOVED***anchorEl:***REMOVED***HTMLElement***REMOVED***|***REMOVED***null***REMOVED***|***REMOVED***{***REMOVED***mouseX:***REMOVED***number;***REMOVED***mouseY:***REMOVED***number***REMOVED***}***REMOVED***|***REMOVED***null;
***REMOVED******REMOVED***onClose:***REMOVED***()***REMOVED***=>***REMOVED***void;
***REMOVED******REMOVED***contextItem:***REMOVED***T***REMOVED***|***REMOVED***null;
}

const***REMOVED***GenericContextMenu***REMOVED***=***REMOVED***<T,>({
***REMOVED******REMOVED***items,
***REMOVED******REMOVED***anchorEl,
***REMOVED******REMOVED***onClose,
***REMOVED******REMOVED***contextItem,
}:***REMOVED***Props<T>)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Menu
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***anchorEl={typeof***REMOVED***anchorEl***REMOVED***!==***REMOVED***"object"***REMOVED***?***REMOVED***anchorEl***REMOVED***:***REMOVED***undefined}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***open={Boolean(anchorEl)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClose={onClose}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***anchorReference={
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***anchorEl***REMOVED***&&***REMOVED***typeof***REMOVED***anchorEl***REMOVED***===***REMOVED***"object"***REMOVED***&&***REMOVED***"mouseX"***REMOVED***in***REMOVED***anchorEl
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***"anchorPosition"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***"anchorEl"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***anchorPosition={
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***anchorEl***REMOVED***&&***REMOVED***typeof***REMOVED***anchorEl***REMOVED***===***REMOVED***"object"***REMOVED***&&***REMOVED***"mouseX"***REMOVED***in***REMOVED***anchorEl
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***{***REMOVED***top:***REMOVED***anchorEl.mouseY,***REMOVED***left:***REMOVED***anchorEl.mouseX***REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***undefined
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***PaperProps={{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sx:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***borderRadius:***REMOVED***2,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***minWidth:***REMOVED***160,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***backgroundColor:***REMOVED***"#fff",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***boxShadow:***REMOVED***"0px***REMOVED***4px***REMOVED***12px***REMOVED***rgba(0,0,0,0.1)",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***paddingY:***REMOVED***0.5,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{items.map((item,***REMOVED***index)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<MenuItem
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***key={item.id}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClick={()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***item.onClick?.(contextItem!);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClose();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sx={{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***fontSize:***REMOVED***"14px",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***paddingY:***REMOVED***"6px",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***borderBottom:
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***index***REMOVED***!==***REMOVED***items.length***REMOVED***-***REMOVED***1***REMOVED***?***REMOVED***"1px***REMOVED***solid***REMOVED***#dcdcdc"***REMOVED***:***REMOVED***"none",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"&:hover":***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***backgroundColor:***REMOVED***"#f5f5f5",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{item.icon***REMOVED***&&***REMOVED***<ListItemIcon>{item.icon}</ListItemIcon>}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ListItemText***REMOVED***primary={item.label}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</MenuItem>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED***</Menu>
***REMOVED******REMOVED***);
};

export***REMOVED***default***REMOVED***GenericContextMenu;
