import***REMOVED***React***REMOVED***from***REMOVED***"react";
import***REMOVED***{
***REMOVED******REMOVED***Dialog,
***REMOVED******REMOVED***DialogTitle,
***REMOVED******REMOVED***DialogContent,
***REMOVED******REMOVED***DialogActions,
***REMOVED******REMOVED***Button,
***REMOVED******REMOVED***Typography,
}***REMOVED***from***REMOVED***"@mui/material";
import***REMOVED***WarningAmberIcon***REMOVED***from***REMOVED***"@mui/icons-material/WarningAmber";

interface***REMOVED***ModalConfirmProps***REMOVED***{
***REMOVED******REMOVED***open:***REMOVED***boolean;
***REMOVED******REMOVED***title?:***REMOVED***string;
***REMOVED******REMOVED***message:***REMOVED***string***REMOVED***|***REMOVED***string[];
***REMOVED******REMOVED***onClose:***REMOVED***()***REMOVED***=>***REMOVED***void;
***REMOVED******REMOVED***onConfirm:***REMOVED***()***REMOVED***=>***REMOVED***void;
***REMOVED******REMOVED***confirmText?:***REMOVED***string;
***REMOVED******REMOVED***cancelText?:***REMOVED***string;
***REMOVED******REMOVED***showConfirmButton?:***REMOVED***boolean;
}

const***REMOVED***ModalConfirm:***REMOVED***React.FC<ModalConfirmProps>***REMOVED***=***REMOVED***({
***REMOVED******REMOVED***open,
***REMOVED******REMOVED***title***REMOVED***=***REMOVED***"Xác***REMOVED***nhận",
***REMOVED******REMOVED***message,
***REMOVED******REMOVED***onClose,
***REMOVED******REMOVED***onConfirm,
***REMOVED******REMOVED***confirmText***REMOVED***=***REMOVED***"Xác***REMOVED***nhận",
***REMOVED******REMOVED***cancelText***REMOVED***=***REMOVED***"Hủy",
***REMOVED******REMOVED***showConfirmButton,
})***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Dialog***REMOVED***open={open}***REMOVED***onClose={onClose}***REMOVED***maxWidth="sm"***REMOVED***fullWidth>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogTitle***REMOVED***sx={{***REMOVED***display:***REMOVED***"flex",***REMOVED***alignItems:***REMOVED***"center",***REMOVED***gap:***REMOVED***1***REMOVED***}}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<WarningAmberIcon***REMOVED***color="warning"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{title}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogTitle>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogContent***REMOVED***sx={{***REMOVED***maxHeight:***REMOVED***300,***REMOVED***overflowY:***REMOVED***"auto"***REMOVED***}}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{Array.isArray(message)***REMOVED***?***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Typography***REMOVED***variant="body2"***REMOVED***sx={{***REMOVED***mb:***REMOVED***1***REMOVED***}}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{message[0]}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Typography>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ul***REMOVED***style={{***REMOVED***paddingLeft:***REMOVED***"1.2em"***REMOVED***}}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{message.slice(1).map((msg,***REMOVED***index)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<li***REMOVED***key={index}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Typography***REMOVED***variant="body2">{msg}</Typography>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</li>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</ul>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)***REMOVED***:***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Typography***REMOVED***variant="body2">{message}</Typography>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogContent>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogActions***REMOVED***sx={{***REMOVED***px:***REMOVED***3,***REMOVED***pb:***REMOVED***2***REMOVED***}}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Button
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant="contained"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***color={showConfirmButton***REMOVED***?***REMOVED***"error"***REMOVED***:***REMOVED***"inherit"}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***disabled={!showConfirmButton}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClick={onConfirm}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sx={!showConfirmButton***REMOVED***?***REMOVED***{***REMOVED***opacity:***REMOVED***0.6,***REMOVED***cursor:***REMOVED***"not-allowed"***REMOVED***}***REMOVED***:***REMOVED***{}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{confirmText}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Button***REMOVED***variant="outlined"***REMOVED***onClick={onClose}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{cancelText}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogActions>
***REMOVED******REMOVED******REMOVED******REMOVED***</Dialog>
***REMOVED******REMOVED***);
};

export***REMOVED***default***REMOVED***ModalConfirm;
