import***REMOVED***React***REMOVED***from***REMOVED***"react";
import***REMOVED***{
***REMOVED******REMOVED***Dialog,
***REMOVED******REMOVED***DialogTitle,
***REMOVED******REMOVED***DialogContent,
***REMOVED******REMOVED***DialogActions,
***REMOVED******REMOVED***Button,
***REMOVED******REMOVED***Typography,
}***REMOVED***from***REMOVED***"@mui/material";
import***REMOVED***WarningAmberIcon***REMOVED***from***REMOVED***"@mui/icons-material/WarningAmber";

interface***REMOVED***ModalConfirmProps***REMOVED***{
***REMOVED******REMOVED***open:***REMOVED***boolean;
***REMOVED******REMOVED***title?:***REMOVED***string;
***REMOVED******REMOVED***message:***REMOVED***string;
***REMOVED******REMOVED***onClose:***REMOVED***()***REMOVED***=>***REMOVED***void;
***REMOVED******REMOVED***onConfirm:***REMOVED***()***REMOVED***=>***REMOVED***void;
***REMOVED******REMOVED***confirmText?:***REMOVED***string;
***REMOVED******REMOVED***cancelText?:***REMOVED***string;
}

const***REMOVED***ModalConfirm:***REMOVED***React.FC<ModalConfirmProps>***REMOVED***=***REMOVED***({
***REMOVED******REMOVED***open,
***REMOVED******REMOVED***title***REMOVED***=***REMOVED***"Xác***REMOVED***nhận",
***REMOVED******REMOVED***message,
***REMOVED******REMOVED***onClose,
***REMOVED******REMOVED***onConfirm,
***REMOVED******REMOVED***confirmText***REMOVED***=***REMOVED***"Xác***REMOVED***nhận",
***REMOVED******REMOVED***cancelText***REMOVED***=***REMOVED***"Hủy",
})***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Dialog***REMOVED***open={open}***REMOVED***onClose={onClose}***REMOVED***maxWidth="xs"***REMOVED***fullWidth>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogTitle***REMOVED***sx={{***REMOVED***display:***REMOVED***"flex",***REMOVED***alignItems:***REMOVED***"center",***REMOVED***gap:***REMOVED***1***REMOVED***}}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<WarningAmberIcon***REMOVED***color="warning"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{title}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogTitle>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogContent>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Typography***REMOVED***variant="body2">{message}</Typography>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogContent>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogActions***REMOVED***sx={{***REMOVED***px:***REMOVED***3,***REMOVED***pb:***REMOVED***2***REMOVED***}}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Button***REMOVED***variant="outlined"***REMOVED***onClick={onClose}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{cancelText}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Button***REMOVED***variant="contained"***REMOVED***color="error"***REMOVED***onClick={onConfirm}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{confirmText}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogActions>
***REMOVED******REMOVED******REMOVED******REMOVED***</Dialog>
***REMOVED******REMOVED***);
};

export***REMOVED***default***REMOVED***ModalConfirm;
