import***REMOVED***React,***REMOVED***{***REMOVED***useState***REMOVED***}***REMOVED***from***REMOVED***"react";
import***REMOVED***{***REMOVED***Drawer,***REMOVED***List,***REMOVED***ListItem,***REMOVED***ListItemIcon,***REMOVED***ListItemText,***REMOVED***IconButton,***REMOVED***Tooltip***REMOVED***}***REMOVED***from***REMOVED***"@mui/material";
import***REMOVED***{***REMOVED***Dashboard,***REMOVED***People,***REMOVED***Settings,***REMOVED***ChevronLeft,***REMOVED***ChevronRight,***REMOVED***CategoryOutlined***REMOVED***}***REMOVED***from***REMOVED***"@mui/icons-material";
import***REMOVED***{***REMOVED***Link***REMOVED***}***REMOVED***from***REMOVED***"react-router-dom";
import***REMOVED***{***REMOVED***useTheme***REMOVED***}***REMOVED***from***REMOVED***"@mui/material/styles";
import***REMOVED***{***REMOVED***useMediaQuery***REMOVED***}***REMOVED***from***REMOVED***"@mui/material";

const***REMOVED***Sidebar:***REMOVED***React.FC***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***[expanded,***REMOVED***setExpanded]***REMOVED***=***REMOVED***useState(true);
***REMOVED******REMOVED***const***REMOVED***theme***REMOVED***=***REMOVED***useTheme();
***REMOVED******REMOVED***const***REMOVED***isMobile***REMOVED***=***REMOVED***useMediaQuery(theme.breakpoints.down("md"));

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Drawer
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant={isMobile***REMOVED***?***REMOVED***"temporary"***REMOVED***:***REMOVED***"permanent"}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***open={expanded}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClose={()***REMOVED***=>***REMOVED***setExpanded(false)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sx={{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***width:***REMOVED***expanded***REMOVED***?***REMOVED***240***REMOVED***:***REMOVED***80,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***height:***REMOVED***"100vh",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***flexShrink:***REMOVED***0,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***"&***REMOVED***.MuiDrawer-paper":***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***width:***REMOVED***expanded***REMOVED***?***REMOVED***240***REMOVED***:***REMOVED***80,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***transition:***REMOVED***"width***REMOVED***0.3s",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***overflowX:***REMOVED***"hidden",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***display:***REMOVED***"flex",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***flexDirection:***REMOVED***"column",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***alignItems:***REMOVED***"center",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***position:***REMOVED***"relative",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Danh***REMOVED***sách***REMOVED***menu***REMOVED***(VẪN***REMOVED***Ở***REMOVED***TRÊN)***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<List***REMOVED***sx={{***REMOVED***width:***REMOVED***"100%"***REMOVED***}}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Tooltip***REMOVED***title="Dashboard"***REMOVED***placement="right"***REMOVED***disableHoverListener={expanded}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ListItem***REMOVED***component={Link}***REMOVED***to="/dashboard"***REMOVED***sx={{***REMOVED***cursor:***REMOVED***"pointer",***REMOVED***justifyContent:***REMOVED***"center"***REMOVED***}}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ListItemIcon><Dashboard***REMOVED***/></ListItemIcon>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{expanded***REMOVED***&&***REMOVED***<ListItemText***REMOVED***primary="Dashboard"***REMOVED***/>}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</ListItem>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Tooltip>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Tooltip***REMOVED***title="category"***REMOVED***placement="right"***REMOVED***disableHoverListener={expanded}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ListItem***REMOVED***component={Link}***REMOVED***to="/category"***REMOVED***sx={{***REMOVED***cursor:***REMOVED***"pointer",***REMOVED***justifyContent:***REMOVED***"center"***REMOVED***}}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ListItemIcon><CategoryOutlined***REMOVED***/></ListItemIcon>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{expanded***REMOVED***&&***REMOVED***<ListItemText***REMOVED***primary="Danh***REMOVED***Mục"***REMOVED***/>}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</ListItem>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Tooltip>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Tooltip***REMOVED***title="Users"***REMOVED***placement="right"***REMOVED***disableHoverListener={expanded}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ListItem***REMOVED***component={Link}***REMOVED***to="/users"***REMOVED***sx={{***REMOVED***cursor:***REMOVED***"pointer",***REMOVED***justifyContent:***REMOVED***"center"***REMOVED***}}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ListItemIcon><People***REMOVED***/></ListItemIcon>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{expanded***REMOVED***&&***REMOVED***<ListItemText***REMOVED***primary="Users"***REMOVED***/>}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</ListItem>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Tooltip>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Tooltip***REMOVED***title="Settings"***REMOVED***placement="right"***REMOVED***disableHoverListener={expanded}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ListItem***REMOVED***component={Link}***REMOVED***to="/settings"***REMOVED***sx={{***REMOVED***cursor:***REMOVED***"pointer",***REMOVED***justifyContent:***REMOVED***"center"***REMOVED***}}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<ListItemIcon><Settings***REMOVED***/></ListItemIcon>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{expanded***REMOVED***&&***REMOVED***<ListItemText***REMOVED***primary="Settings"***REMOVED***/>}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</ListItem>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Tooltip>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</List>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{/****REMOVED***Nút***REMOVED***Toggle***REMOVED***(Căn***REMOVED***giữa***REMOVED***theo***REMOVED***chiều***REMOVED***dọc,***REMOVED***menu***REMOVED***vẫn***REMOVED***ở***REMOVED***trên)***REMOVED****/}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<IconButton***REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClick={()***REMOVED***=>***REMOVED***setExpanded(!expanded)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sx={{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***position:***REMOVED***"absolute",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***top:***REMOVED***"50%",***REMOVED***//***REMOVED***Đặt***REMOVED***giữa***REMOVED***Sidebar***REMOVED***theo***REMOVED***chiều***REMOVED***dọc
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***transform:***REMOVED***"translateY(-50%)",***REMOVED***//***REMOVED***Dịch***REMOVED***lên***REMOVED***50%***REMOVED***để***REMOVED***chính***REMOVED***giữa
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED******REMOVED******REMOVED***marginRight:***REMOVED***"3px",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***right:***REMOVED***0,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{expanded***REMOVED***?***REMOVED***<ChevronLeft***REMOVED***/>***REMOVED***:***REMOVED***<ChevronRight***REMOVED***/>}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</IconButton>
***REMOVED******REMOVED******REMOVED******REMOVED***</Drawer>
***REMOVED******REMOVED***)
}

export***REMOVED***default***REMOVED***Sidebar
