//***REMOVED***src/components/Toast.tsx
import***REMOVED***{***REMOVED***VariantType,***REMOVED***useSnackbar***REMOVED***}***REMOVED***from***REMOVED***"notistack";
import***REMOVED***{***REMOVED***useCallback***REMOVED***}***REMOVED***from***REMOVED***"react";
import***REMOVED***CheckCircleIcon***REMOVED***from***REMOVED***"@mui/icons-material/CheckCircle";
import***REMOVED***ErrorIcon***REMOVED***from***REMOVED***"@mui/icons-material/Error";
import***REMOVED***InfoIcon***REMOVED***from***REMOVED***"@mui/icons-material/Info";
import***REMOVED***WarningIcon***REMOVED***from***REMOVED***"@mui/icons-material/Warning";
import***REMOVED***{***REMOVED***Box,***REMOVED***Typography***REMOVED***}***REMOVED***from***REMOVED***"@mui/material";

const***REMOVED***getIcon***REMOVED***=***REMOVED***(variant:***REMOVED***VariantType)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***switch***REMOVED***(variant)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***case***REMOVED***"success":
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***<CheckCircleIcon***REMOVED***sx={{***REMOVED***color:***REMOVED***"green",***REMOVED***mr:***REMOVED***1,***REMOVED***fontSize:***REMOVED***22***REMOVED***}}***REMOVED***/>;
***REMOVED******REMOVED******REMOVED******REMOVED***case***REMOVED***"error":
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***<ErrorIcon***REMOVED***sx={{***REMOVED***color:***REMOVED***"red",***REMOVED***mr:***REMOVED***1,***REMOVED***fontSize:***REMOVED***22***REMOVED***}}***REMOVED***/>;
***REMOVED******REMOVED******REMOVED******REMOVED***case***REMOVED***"info":
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***<InfoIcon***REMOVED***sx={{***REMOVED***color:***REMOVED***"blue",***REMOVED***mr:***REMOVED***1,***REMOVED***fontSize:***REMOVED***22***REMOVED***}}***REMOVED***/>;
***REMOVED******REMOVED******REMOVED******REMOVED***case***REMOVED***"warning":
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***<WarningIcon***REMOVED***sx={{***REMOVED***color:***REMOVED***"orange",***REMOVED***mr:***REMOVED***1,***REMOVED***fontSize:***REMOVED***22***REMOVED***}}***REMOVED***/>;
***REMOVED******REMOVED******REMOVED******REMOVED***default:
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***null;
***REMOVED******REMOVED***}
};

const***REMOVED***useToast***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***enqueueSnackbar***REMOVED***}***REMOVED***=***REMOVED***useSnackbar();

***REMOVED******REMOVED***const***REMOVED***showToast***REMOVED***=***REMOVED***useCallback(
***REMOVED******REMOVED******REMOVED******REMOVED***(message:***REMOVED***string,***REMOVED***variant:***REMOVED***VariantType***REMOVED***=***REMOVED***"default")***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***enqueueSnackbar(message,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***content:***REMOVED***(key,***REMOVED***message)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Box
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***id={key.toString()}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***display="flex"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***alignItems="center"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***justifyContent=***REMOVED***"center"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***bgcolor="#fff"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***borderRadius={1.5}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***boxShadow={2}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***px={2}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***py={1}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sx={{***REMOVED***minWidth:***REMOVED***180,***REMOVED***maxWidth:***REMOVED***210***REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{getIcon(variant)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Typography
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant="body2"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***fontWeight={700}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***noWrap
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sx={{***REMOVED***flexGrow:***REMOVED***1***REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{message}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Typography>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Box>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***anchorOrigin:***REMOVED***{***REMOVED***vertical:***REMOVED***"top",***REMOVED***horizontal:***REMOVED***"right"***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***autoHideDuration:***REMOVED***2000,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***[enqueueSnackbar]
***REMOVED******REMOVED***);

***REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***showSuccess:***REMOVED***(msg:***REMOVED***string)***REMOVED***=>***REMOVED***showToast(msg,***REMOVED***"success"),
***REMOVED******REMOVED******REMOVED******REMOVED***showError:***REMOVED***(msg:***REMOVED***string)***REMOVED***=>***REMOVED***showToast(msg,***REMOVED***"error"),
***REMOVED******REMOVED******REMOVED******REMOVED***showInfo:***REMOVED***(msg:***REMOVED***string)***REMOVED***=>***REMOVED***showToast(msg,***REMOVED***"info"),
***REMOVED******REMOVED******REMOVED******REMOVED***showWarning:***REMOVED***(msg:***REMOVED***string)***REMOVED***=>***REMOVED***showToast(msg,***REMOVED***"warning"),
***REMOVED******REMOVED***};
};

export***REMOVED***default***REMOVED***useToast;