export***REMOVED***interface***REMOVED***Brand***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***number;
***REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***string;
***REMOVED******REMOVED***}
***REMOVED******REMOVED***
***REMOVED******REMOVED***export***REMOVED***interface***REMOVED***Category***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***number;
***REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***string;
***REMOVED******REMOVED***}
***REMOVED******REMOVED***
***REMOVED******REMOVED***export***REMOVED***interface***REMOVED***Attribute***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***id:***REMOVED***number;
***REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***string;
***REMOVED******REMOVED******REMOVED******REMOVED***value:***REMOVED***string;
***REMOVED******REMOVED***}
***REMOVED******REMOVED***
***REMOVED******REMOVED***export***REMOVED***const***REMOVED***brands:***REMOVED***Brand[]***REMOVED***=***REMOVED***[
***REMOVED******REMOVED******REMOVED******REMOVED***{***REMOVED***id:***REMOVED***1,***REMOVED***name:***REMOVED***"Brand***REMOVED***A"***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{***REMOVED***id:***REMOVED***2,***REMOVED***name:***REMOVED***"Brand***REMOVED***B"***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{***REMOVED***id:***REMOVED***3,***REMOVED***name:***REMOVED***"Brand***REMOVED***C"***REMOVED***},
***REMOVED******REMOVED***];
***REMOVED******REMOVED***
***REMOVED******REMOVED***export***REMOVED***const***REMOVED***categories:***REMOVED***Category[]***REMOVED***=***REMOVED***[
***REMOVED******REMOVED******REMOVED******REMOVED***{***REMOVED***id:***REMOVED***1,***REMOVED***name:***REMOVED***"Đồ***REMOVED***uống"***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{***REMOVED***id:***REMOVED***2,***REMOVED***name:***REMOVED***"Thực***REMOVED***phẩm"***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{***REMOVED***id:***REMOVED***3,***REMOVED***name:***REMOVED***"Đồ***REMOVED***gia***REMOVED***dụng"***REMOVED***},
***REMOVED******REMOVED***];
***REMOVED******REMOVED***
***REMOVED******REMOVED***export***REMOVED***const***REMOVED***attributes:***REMOVED***Attribute[]***REMOVED***=***REMOVED***[
***REMOVED******REMOVED******REMOVED******REMOVED***{***REMOVED***id:***REMOVED***1,***REMOVED***name:***REMOVED***"Trọng***REMOVED***lượng",***REMOVED***value:***REMOVED***"500g"***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{***REMOVED***id:***REMOVED***2,***REMOVED***name:***REMOVED***"Kích***REMOVED***thước",***REMOVED***value:***REMOVED***"20x30cm"***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{***REMOVED***id:***REMOVED***3,***REMOVED***name:***REMOVED***"Màu***REMOVED***sắc",***REMOVED***value:***REMOVED***"Xanh"***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{***REMOVED***id:***REMOVED***4,***REMOVED***name:***REMOVED***"Chất***REMOVED***liệu",***REMOVED***value:***REMOVED***"Nhựa"***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{***REMOVED***id:***REMOVED***5,***REMOVED***name:***REMOVED***"Hạn***REMOVED***sử***REMOVED***dụng",***REMOVED***value:***REMOVED***"12***REMOVED***tháng"***REMOVED***},
***REMOVED******REMOVED***];