import***REMOVED***{***REMOVED***createTheme***REMOVED***}***REMOVED***from***REMOVED***"@mui/material/styles";

const***REMOVED***theme***REMOVED***=***REMOVED***createTheme({
***REMOVED******REMOVED***palette:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***mode:***REMOVED***"light",***REMOVED***//***REMOVED***hoặc***REMOVED***dark***REMOVED***nếu***REMOVED***cần
***REMOVED******REMOVED******REMOVED******REMOVED***primary:***REMOVED***{***REMOVED***main:***REMOVED***"#007bff"***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***secondary:***REMOVED***{***REMOVED***main:***REMOVED***"#ff4081"***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***background:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***default:***REMOVED***"#f5f5f5",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***paper:***REMOVED***"#ffffff",
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***text:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***primary:***REMOVED***"#000000",
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED***},
***REMOVED******REMOVED***breakpoints:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***values:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***xs:***REMOVED***0,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sm:***REMOVED***600,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***md:***REMOVED***900,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***lg:***REMOVED***1200,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***xl:***REMOVED***1536,
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED***},
});
export***REMOVED***default***REMOVED***theme;
