import***REMOVED***{
***REMOVED******REMOVED***Button,
***REMOVED******REMOVED***Checkbox,
***REMOVED******REMOVED***CircularProgress,
***REMOVED******REMOVED***Dialog,
***REMOVED******REMOVED***DialogActions,
***REMOVED******REMOVED***DialogContent,
***REMOVED******REMOVED***DialogTitle,
***REMOVED******REMOVED***FormControlLabel,
***REMOVED******REMOVED***Grid,
}***REMOVED***from***REMOVED***"@mui/material";
import***REMOVED***{
***REMOVED******REMOVED***useInfiniteQuery,
***REMOVED******REMOVED***useQuery,
}***REMOVED***from***REMOVED***"@tanstack/react-query";
import***REMOVED***InfiniteScroll***REMOVED***from***REMOVED***"react-infinite-scroll-component";
import***REMOVED***{***REMOVED***useEffect,***REMOVED***useState***REMOVED***}***REMOVED***from***REMOVED***"react";
import***REMOVED***{***REMOVED***IAttribute***REMOVED***}***REMOVED***from***REMOVED***"src/Interfaces/IAttribute";
import***REMOVED***attributeApi***REMOVED***from***REMOVED***"src/services/api/Attributes";
import***REMOVED***categoryApi***REMOVED***from***REMOVED***"src/services/api/Category";
import***REMOVED***useToast***REMOVED***from***REMOVED***"src/components/Toast";

interface***REMOVED***Props***REMOVED***{
***REMOVED******REMOVED***categoryId:***REMOVED***number;
***REMOVED******REMOVED***open:***REMOVED***boolean;
***REMOVED******REMOVED***onClose:***REMOVED***()***REMOVED***=>***REMOVED***void;
***REMOVED******REMOVED***onUpdated?:***REMOVED***()***REMOVED***=>***REMOVED***void;
}

const***REMOVED***AddAttributeToCategory***REMOVED***=***REMOVED***({***REMOVED***categoryId,***REMOVED***open,***REMOVED***onClose,***REMOVED***onUpdated***REMOVED***}:***REMOVED***Props)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***[selected,***REMOVED***setSelected]***REMOVED***=***REMOVED***useState<number[]>([]);
***REMOVED******REMOVED***const***REMOVED***[initialSelected,***REMOVED***setInitialSelected]***REMOVED***=***REMOVED***useState<number[]>([]);
***REMOVED******REMOVED***const***REMOVED***[touched,***REMOVED***setTouched]***REMOVED***=***REMOVED***useState<Set<number>>(new***REMOVED***Set());
***REMOVED******REMOVED***const***REMOVED***pageSize***REMOVED***=***REMOVED***20;
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***showSuccess,***REMOVED***showError***REMOVED***}***REMOVED***=***REMOVED***useToast();

***REMOVED******REMOVED***const***REMOVED***{***REMOVED***data,***REMOVED***fetchNextPage,***REMOVED***hasNextPage,***REMOVED***isLoading***REMOVED***}***REMOVED***=***REMOVED***useInfiniteQuery({
***REMOVED******REMOVED******REMOVED******REMOVED***queryKey:***REMOVED***["attributes"],
***REMOVED******REMOVED******REMOVED******REMOVED***queryFn:***REMOVED***async***REMOVED***({***REMOVED***pageParam***REMOVED***=***REMOVED***1***REMOVED***})***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***res***REMOVED***=***REMOVED***await***REMOVED***attributeApi.getPagingApi({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***pageNumber:***REMOVED***pageParam,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***pageSize,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***items:***REMOVED***res.data.items.$values,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***nextPage:
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***res.data.currentPage***REMOVED***<***REMOVED***res.data.totalPages
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***?***REMOVED***pageParam***REMOVED***+***REMOVED***1
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:***REMOVED***undefined,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***};
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***getNextPageParam:***REMOVED***(lastPage)***REMOVED***=>***REMOVED***lastPage.nextPage,
***REMOVED******REMOVED******REMOVED******REMOVED***initialPageParam:***REMOVED***1,
***REMOVED******REMOVED******REMOVED******REMOVED***enabled:***REMOVED***open,
***REMOVED******REMOVED***});

***REMOVED******REMOVED***const***REMOVED***{***REMOVED***data:***REMOVED***selectedAttributesRes,***REMOVED***}***REMOVED***=***REMOVED***useQuery({
***REMOVED******REMOVED******REMOVED******REMOVED***queryKey:***REMOVED***["selectedAttributesRes",***REMOVED***categoryId],
***REMOVED******REMOVED******REMOVED******REMOVED***queryFn:***REMOVED***()***REMOVED***=>***REMOVED***categoryApi.getAttributeById(categoryId),
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***enabled:***REMOVED***open,
***REMOVED******REMOVED***});

***REMOVED******REMOVED***useEffect(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(open***REMOVED***&&***REMOVED***selectedAttributesRes?.data?.$values)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setInitialSelected(selectedAttributesRes.data.$values);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setSelected(selectedAttributesRes.data.$values);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setTouched(new***REMOVED***Set());
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!open)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setInitialSelected([]);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setSelected([]);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setTouched(new***REMOVED***Set());
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***},***REMOVED***[open,***REMOVED***selectedAttributesRes]);

***REMOVED******REMOVED***const***REMOVED***handleToggle***REMOVED***=***REMOVED***(id:***REMOVED***number)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***setSelected((prev)***REMOVED***=>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***prev.includes(id)***REMOVED***?***REMOVED***prev.filter((i)***REMOVED***=>***REMOVED***i***REMOVED***!==***REMOVED***id)***REMOVED***:***REMOVED***[...prev,***REMOVED***id]
***REMOVED******REMOVED******REMOVED******REMOVED***);
***REMOVED******REMOVED******REMOVED******REMOVED***setTouched((prev)***REMOVED***=>***REMOVED***new***REMOVED***Set(prev).add(id));
***REMOVED******REMOVED***};

***REMOVED******REMOVED***const***REMOVED***handleSubmit***REMOVED***=***REMOVED***async***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***added:***REMOVED***number[]***REMOVED***=***REMOVED***[];
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***removed:***REMOVED***number[]***REMOVED***=***REMOVED***[];

***REMOVED******REMOVED******REMOVED******REMOVED***touched.forEach((id)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***wasSelectedInitially***REMOVED***=***REMOVED***initialSelected.includes(id);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***isSelectedNow***REMOVED***=***REMOVED***selected.includes(id);

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(wasSelectedInitially***REMOVED***&&***REMOVED***!isSelectedNow)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***removed.push(id);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!wasSelectedInitially***REMOVED***&&***REMOVED***isSelectedNow)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***added.push(id);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***finalList***REMOVED***=***REMOVED***[...added,***REMOVED***...removed];

***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***categoryApi.setAttributesForCategory({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***categoryId,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***attributeIds:***REMOVED***finalList,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onUpdated?.();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***showSuccess("Sửa***REMOVED***thành***REMOVED***công!");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClose();
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(err)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***showError("Sửa***REMOVED***thất***REMOVED***bại");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error("Lỗi***REMOVED***khi***REMOVED***cập***REMOVED***nhật***REMOVED***thuộc***REMOVED***tính:",***REMOVED***err);
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***};

***REMOVED******REMOVED***const***REMOVED***allAttributes***REMOVED***=
***REMOVED******REMOVED******REMOVED******REMOVED***data?.pages.flatMap((page)***REMOVED***=>***REMOVED***page.items***REMOVED***as***REMOVED***IAttribute[])***REMOVED***||***REMOVED***[];

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Dialog***REMOVED***open={open}***REMOVED***onClose={onClose}***REMOVED***fullWidth***REMOVED***maxWidth="lg">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogTitle>Thêm***REMOVED***thuộc***REMOVED***tính***REMOVED***vào***REMOVED***danh***REMOVED***mục</DialogTitle>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogContent
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***id="scrollable-attribute-list"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sx={{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***maxHeight:***REMOVED***"70vh",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***overflowY:***REMOVED***"auto",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***paddingRight:***REMOVED***"12px",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{isLoading***REMOVED***?***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<CircularProgress***REMOVED***size={24}***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)***REMOVED***:***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<InfiniteScroll
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***dataLength={allAttributes.length}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***next={fetchNextPage}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hasMore={!!hasNextPage}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***loader={<CircularProgress***REMOVED***size={20}***REMOVED***/>}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***scrollableTarget="scrollable-attribute-list"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Grid***REMOVED***container***REMOVED***spacing={2}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{allAttributes.map((attr)***REMOVED***=>***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Grid***REMOVED***item***REMOVED***xs={12}***REMOVED***sm={6}***REMOVED***md={4}***REMOVED***lg={3}***REMOVED***key={attr.attributeId}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<FormControlLabel
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***control={
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Checkbox
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***checked={selected.includes(attr.attributeId)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onChange={()***REMOVED***=>***REMOVED***handleToggle(attr.attributeId)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label={attr.name}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Grid>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***))}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Grid>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</InfiniteScroll>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogContent>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogActions>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Button***REMOVED***onClick={onClose}>Hủy</Button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Button***REMOVED***onClick={handleSubmit}***REMOVED***variant="contained">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Lưu
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogActions>
***REMOVED******REMOVED******REMOVED******REMOVED***</Dialog>
***REMOVED******REMOVED***);
};

export***REMOVED***default***REMOVED***AddAttributeToCategory;
