import***REMOVED***React,***REMOVED***{***REMOVED***useEffect,***REMOVED***useState***REMOVED***}***REMOVED***from***REMOVED***"react";
import***REMOVED***{
***REMOVED******REMOVED***Dialog,
***REMOVED******REMOVED***DialogTitle,
***REMOVED******REMOVED***DialogContent,
***REMOVED******REMOVED***DialogActions,
***REMOVED******REMOVED***TextField,
***REMOVED******REMOVED***Button,
}***REMOVED***from***REMOVED***"@mui/material";
import***REMOVED***LockIcon***REMOVED***from***REMOVED***"@mui/icons-material/Lock";
import***REMOVED***{***REMOVED***useMutation,***REMOVED***useQueryClient***REMOVED***}***REMOVED***from***REMOVED***"@tanstack/react-query";
import***REMOVED***{***REMOVED***IAddCategoryRequest,***REMOVED***ICategory***REMOVED***}***REMOVED***from***REMOVED***"src/Interfaces/ICategory";
import***REMOVED***categoryApi***REMOVED***from***REMOVED***"src/services/api/Category";
import***REMOVED***useToast***REMOVED***from***REMOVED***"src/components/Toast";

interface***REMOVED***Props***REMOVED***{
***REMOVED******REMOVED***open:***REMOVED***boolean;
***REMOVED******REMOVED***onClose:***REMOVED***()***REMOVED***=>***REMOVED***void;
***REMOVED******REMOVED***parentCategoryName?:***REMOVED***string***REMOVED***|***REMOVED***null;
***REMOVED******REMOVED***parentCategoryId?:***REMOVED***number;
***REMOVED******REMOVED***category:***REMOVED***ICategory***REMOVED***|***REMOVED***null;
}

const***REMOVED***UpdateCategoryModal***REMOVED***=***REMOVED***({
***REMOVED******REMOVED***open,
***REMOVED******REMOVED***onClose,
***REMOVED******REMOVED***category,
***REMOVED******REMOVED***parentCategoryName,
}:***REMOVED***Props)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***[name,***REMOVED***setName]***REMOVED***=***REMOVED***useState("");
***REMOVED******REMOVED***const***REMOVED***[description,***REMOVED***setDescription]***REMOVED***=***REMOVED***useState("");
***REMOVED******REMOVED***const***REMOVED***[error,***REMOVED***setError]***REMOVED***=***REMOVED***useState(false);
***REMOVED******REMOVED***const***REMOVED***{***REMOVED***showSuccess,***REMOVED***showError***REMOVED***}***REMOVED***=***REMOVED***useToast();

***REMOVED******REMOVED***const***REMOVED***queryClient***REMOVED***=***REMOVED***useQueryClient();

***REMOVED******REMOVED***useEffect(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(open***REMOVED***&&***REMOVED***category)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setName(category.categoryName***REMOVED***??***REMOVED***"");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setDescription(category.description***REMOVED***??***REMOVED***"");
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***},***REMOVED***[open,***REMOVED***category]);

***REMOVED******REMOVED***const***REMOVED***invalidateAllCategoryData***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***queryClient.invalidateQueries({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***predicate:***REMOVED***(query)***REMOVED***=>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***["category",***REMOVED***"categories"].includes(query.queryKey[0]***REMOVED***as***REMOVED***string),
***REMOVED******REMOVED******REMOVED******REMOVED***});
***REMOVED******REMOVED***};

***REMOVED******REMOVED***const***REMOVED***mutation***REMOVED***=***REMOVED***useMutation({
***REMOVED******REMOVED******REMOVED******REMOVED***mutationFn:***REMOVED***(data:***REMOVED***IAddCategoryRequest)***REMOVED***=>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***categoryApi.updateCategoryApi(category?.categoryId!,***REMOVED***data),
***REMOVED******REMOVED******REMOVED******REMOVED***onSuccess:***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***invalidateAllCategoryData();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClose();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***showSuccess("Sửa***REMOVED***thành***REMOVED***công!");
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED***});

***REMOVED******REMOVED***const***REMOVED***handleSubmit***REMOVED***=***REMOVED***async***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!category?.categoryId)***REMOVED***return;
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!name.trim())***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setError(true);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return;
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***setError(false);
***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***mutation.mutateAsync({
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***categoryName:***REMOVED***name,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***description:***REMOVED***description,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***});

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setName("");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setDescription("");
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClose();
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(err)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error("Lỗi***REMOVED***khi***REMOVED***sửa***REMOVED***danh***REMOVED***mục:",***REMOVED***err);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***showError("Sửa***REMOVED***thất***REMOVED***bại!!");
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***};

***REMOVED******REMOVED***return***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***<Dialog
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***open={open}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClose={onClose}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***maxWidth="sm"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***PaperProps={{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sx:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***top:***REMOVED***"50%",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***transform:***REMOVED***"translateY(-70%)",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***position:***REMOVED***"absolute",
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogTitle>Sửa***REMOVED***danh***REMOVED***mục</DialogTitle>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogContent>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{parentCategoryName***REMOVED***&&***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<TextField
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***fullWidth
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label="Danh***REMOVED***mục***REMOVED***cha"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***value={parentCategoryName}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***margin="dense"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***InputProps={{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***readOnly:***REMOVED***true,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sx:***REMOVED***{***REMOVED***opacity:***REMOVED***0.6,***REMOVED***cursor:***REMOVED***"default",***REMOVED***fontWeight:***REMOVED***"bold"***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***endAdornment:***REMOVED***<LockIcon***REMOVED***fontSize="medium"***REMOVED***color="secondary"***REMOVED***/>,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)}

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<TextField
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***fullWidth
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label="Tên***REMOVED***danh***REMOVED***mục"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***margin="dense"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***value={name}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onChange={(e)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setName(e.target.value);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(error***REMOVED***&&***REMOVED***e.target.value.trim())***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setError(false);
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***error={error}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***helperText={error***REMOVED***?***REMOVED***"Vui***REMOVED***lòng***REMOVED***nhập***REMOVED***tên***REMOVED***danh***REMOVED***mục"***REMOVED***:***REMOVED***""}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>

***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<TextField
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***fullWidth
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***label="Mô***REMOVED***tả"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***multiline
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***minRows={4}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***margin="dense"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***value={description}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onChange={(e)***REMOVED***=>***REMOVED***setDescription(e.target.value)}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogContent>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<DialogActions>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Button
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***variant="contained"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onClick={handleSubmit}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***onKeyDown={(e)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(e.key***REMOVED***===***REMOVED***"Enter")***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***e.preventDefault();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***handleSubmit();
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***sx={{***REMOVED***backgroundColor:***REMOVED***"#FFA726",***REMOVED***color:***REMOVED***"white"***REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Sửa
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<Button***REMOVED***variant="outlined"***REMOVED***onClick={onClose}>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***Hủy
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</Button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</DialogActions>
***REMOVED******REMOVED******REMOVED******REMOVED***</Dialog>
***REMOVED******REMOVED***);
};

export***REMOVED***default***REMOVED***UpdateCategoryModal;
